### ISSUE TITLE
Getting Idaliah data

### ISSUE THREAD

**Issue by jcwarner-usgs** [SASlabgroup/SWIFT-codes#31]
Dear Swifters:

thanks for all you are doing.  this is great.
I just did a git update.

1) i ran 
[ allbatterylevels lasttime lastlat lastlon] = pullSWIFTtelemetry( '029', '2023-08-28T00:00:00', '' );

SWIFTtype =
    'micro'
out =
    'E:\data3\Projects\NOPP_hurricanes_modeling\Idalia_2023\Swifts\buoy-microSWIFT 029-start-2023-08-28T00_00_00-end-2023-09-01T00_00_00\SWIFT029.zip'

multiple expanded directories for SWIFT 029
Unrecognized function or variable 'SWIFT'.

Error in pullSWIFTtelemetry (line 121)
if isfield(SWIFT,'watertemp') && ~isempty(SWIFT)

i went to debug mode and when we get to that line, there is no 'SWIFT' var or structure in the workspace.
can you help me with that?
-john

**Comment by jthomson-apluw** [comment]
Hi John, 

Are you running this in an empty directory?  (This is required.)

Also, are you on a PC, Mac, or Linux?

-Jim

----------------------------------
Jim Thomson, PhD
Senior Principal Oceanographer, Applied Physics Lab.
Professor, Civil & Environmental Engineering Dept.  
University of Washington
1013 NE 40th St, Seattle WA 98105
206-999-6908, ***@***.***

**Comment by jthomson-apluw** [comment]
Ok, we’re getting somewhere.  You definitely need to use ‘029’, not ’29’.   

The new error is about the “half-float” precision that we use for spectral values, which is meant to be efficient with the Iridium transmissions.  This requires Matlab R2018a or later.   What version are you using?

**Comment by jcwarner-usgs** [comment]
version
ans =
    '9.12.0.1884302 (R2022a)'

[thanks for your help.  I am thinking to make these drifters - model comparison into my OS abstract]

**Comment by jthomson-apluw** [comment]
I wonder if the half.typecast is part of a toolbox (and we did not realize it).  

If you type “help half” in Matlab, what do you get? 



----------------------------------
Jim Thomson, PhD
Senior Principal Oceanographer, Applied Physics Lab.
Professor, Civil & Environmental Engineering Dept.  
University of Washington
1013 NE 40th St, Seattle WA 98105
206-999-6908, ***@***.***

**Comment by jacobrdavis** [comment]
Yes the half-precision floats are part of a toolbox (which we knew, did not document, and have since forgotten about). I used the "Fixed-Point Designer" toolbox.

**Comment by jthomson-apluw** [comment]
I will add a comment to that code noting that dependency…
