### ISSUE TITLE
bug in MEM_directionalestimator.m

### ISSUE THREAD

**Issue by aliabdolali** [SASlabgroup/SWIFT-codes#50]
Hi Jim, I noticed there is a bug in MEM_directionalestimator.m, otherwise hs is not correct.
https://github.com/SASlabgroup/SWIFT-codes/blob/master/Waves/MEM_directionalestimator.m#L89
tot=sum(S,2)*dtheta; > tot=sum(S,2)*dtheta*dr;

**Comment by jthomson-apluw** [comment]
Thanks Ali— fixing now.

----------------------------------
Jim Thomson, PhD
Senior Principal Oceanographer, Applied Physics Lab
Professor, Civil/Environmental Engineering Dept. 
University of Washington
206-616-0858
